"""Regenerate the freeze's two provenance files.

    MANIFEST.sha256          sha256 of every committed file outside `runs/`
    runs/apt_lab/INVENTORY.md  per-batch inventory: payload(s), policy, run counts, tokens

Why the second file exists: the raw traces are the evidence, but "22 batches and 348 run
artefacts" is a claim about them, and a claim about the evidence should be checkable
without reading 621 JSON files by hand. It also makes the two things that quietly change a
pool visible at a glance -- a batch's payload classification and its void status.

Run from the repository root:  python repro/freeze_manifest.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import chain_stats as cs  # noqa: E402

REPO = _HERE.parent
MANIFEST = REPO / "MANIFEST.sha256"
INVENTORY = cs.ROOT / "INVENTORY.md"


#: Local-only paths, mirroring `.gitignore`. The manifest describes the *published*
#: artifact, so a path that is never committed must never be hashed into it: hashing
#: `secrets/minimax_api_key.txt` would publish a verifier for a live credential, and
#: hashing `__pycache__` would make the manifest depend on which tests were last run.
#: (The first version walked the whole filesystem and listed the key file. It was caught
#: by the check mode on the very next run, which is the point of having one.)
SKIP_PREFIXES = ("runs/", "secrets/", ".git/", ".venv/", ".venv-run/", ".pytest_cache/")
SKIP_PARTS = {"__pycache__"}
SKIP_SUFFIXES = (".pyc",)
SKIP_NAMES = {"MANIFEST.sha256"}


def digested() -> list[str]:
    """Digest every published file except the raw traces and the manifest itself."""

    lines = []
    for path in sorted(REPO.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO).as_posix()
        if rel in SKIP_NAMES or rel.startswith(SKIP_PREFIXES) or rel.endswith(SKIP_SUFFIXES):
            continue
        if any(part in SKIP_PARTS or part in SKIP_NAMES for part in path.parts):
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f"{digest}  {rel}")
    return lines


def manifest() -> int:
    lines = digested()
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"MANIFEST.sha256: {len(lines)} files")
    return len(lines)


def check() -> int:
    """Verify the committed manifest against this working tree.

    Without this, a manifest is decoration: the first version of this file was generated
    once, then nine files were edited during the freeze audit, and nothing said so -- the
    drift only surfaced because a clone was compared against it by hand. A stale manifest
    is worse than no manifest, because it *looks* like verification.
    """

    if not MANIFEST.exists():
        print("MANIFEST.sha256 is missing; run without --check to create it")
        return 1
    expected = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        digest, _, rel = line.partition("  ")
        if rel:
            expected[rel] = digest
    actual = dict(
        (line.split("  ", 1)[1], line.split("  ", 1)[0]) for line in digested()
    )
    missing = sorted(set(expected) - set(actual))
    added = sorted(set(actual) - set(expected))
    changed = sorted(rel for rel in set(expected) & set(actual)
                     if expected[rel] != actual[rel])
    for rel in changed:
        print(f"CHANGED  {rel}")
    for rel in missing:
        print(f"MISSING  {rel}")
    for rel in added:
        print(f"UNLISTED {rel}")
    print(f"manifest check: {len(actual)} files, "
          f"{len(changed)} changed, {len(missing)} missing, {len(added)} unlisted")
    return 1 if (changed or missing or added) else 0


def inventory() -> int:
    rows = []
    total_runs = 0
    total_tokens = 0
    for d in sorted(cs.ROOT.glob("chain-*")):
        if not d.is_dir():
            continue
        runs = cs.runs_of(d)
        if not runs:
            continue
        arms: dict[str, int] = {}
        variants: dict[str, int] = {}
        tokens = 0
        for _stem, j, v, _p in runs:
            arms[j.get("arm", "?")] = arms.get(j.get("arm", "?"), 0) + 1
            variants[v] = variants.get(v, 0) + 1
            tokens += (j.get("usage") or {}).get("total_tokens", 0)
        total_runs += len(runs)
        total_tokens += tokens
        rows.append((
            d.name,
            "/".join(f"{k}x{n}" if n > 1 else k for k, n in sorted(variants.items())),
            cs.policy_of(d) or "?",
            len(runs),
            f"{arms.get('R-forced', 0)}/{arms.get('C0-forced', 0)}",
            f"{tokens / 1e6:.1f}M" if tokens else "-",
            "**VOID**" if d.name in cs.VOID_BATCHES else "",
        ))

    lines = [
        "# Batch inventory",
        "",
        "Generated by `repro/freeze_manifest.py` from the raw artefacts. `R/C0` are the",
        "run counts per arm; `tokens` is `-` for batches that predate the recording proxy.",
        "",
        f"**{len(rows)} batches, {total_runs} run artefacts, "
        f"{total_tokens / 1e6:.1f}M accounted tokens.**",
        "",
        "| batch | payload(s) | policy | runs | R/C0 | tokens | |",
        "|---|---|---|---:|---|---:|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(x) for x in row) + " |")
    lines += [
        "",
        "A void batch is kept rather than deleted: its `VOID.md` records what broke, and a",
        "batch that is missing from the directory listing is indistinguishable from one that",
        "never ran.",
        "",
    ]
    INVENTORY.write_text("\n".join(lines), encoding="utf-8")
    print(f"INVENTORY.md: {len(rows)} batches, {total_runs} runs, "
          f"{total_tokens / 1e6:.1f}M tokens")
    return 0


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed manifest instead of regenerating it")
    args = parser.parse_args()
    if args.check:
        return check()
    manifest()
    inventory()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
