"""Regenerate the freeze's two provenance files.

    MANIFEST.sha256          sha256 of every committed file outside `runs/`
    runs/apt_lab/INVENTORY.md  per-batch inventory: payload(s), policy, run counts, tokens

Why the second file exists: the raw traces are the evidence, but "22 batches and 348 run
artefacts" is a claim about them, and a claim about the evidence should be checkable
without reading 621 JSON files by hand. It also makes the two things that quietly change a
pool visible at a glance -- a batch's payload classification and its void status.

Run from the repository root:  python repro/freeze_manifest.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import chain_stats as cs  # noqa: E402

REPO = _HERE.parent
MANIFEST = REPO / "MANIFEST.sha256"
INVENTORY = cs.ROOT / "INVENTORY.md"


def manifest() -> int:
    """Digest every committed file except the raw traces and the manifest itself."""

    lines = []
    for path in sorted(REPO.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO).as_posix()
        if rel.startswith("runs/") or rel == "MANIFEST.sha256":
            continue
        if any(part in {".git", "__pycache__", ".pytest_cache"} for part in path.parts):
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f"{digest}  {rel}")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"MANIFEST.sha256: {len(lines)} files")
    return len(lines)


def inventory() -> int:
    rows = []
    total_runs = 0
    total_tokens = 0
    for d in sorted(cs.ROOT.glob("chain-*")):
        if not d.is_dir():
            continue
        runs = cs.runs_of(d)
        if not runs:
            continue
        arms: dict[str, int] = {}
        variants: dict[str, int] = {}
        tokens = 0
        for _stem, j, v, _p in runs:
            arms[j.get("arm", "?")] = arms.get(j.get("arm", "?"), 0) + 1
            variants[v] = variants.get(v, 0) + 1
            tokens += (j.get("usage") or {}).get("total_tokens", 0)
        total_runs += len(runs)
        total_tokens += tokens
        rows.append((
            d.name,
            "/".join(f"{k}x{n}" if n > 1 else k for k, n in sorted(variants.items())),
            cs.policy_of(d) or "?",
            len(runs),
            f"{arms.get('R-forced', 0)}/{arms.get('C0-forced', 0)}",
            f"{tokens / 1e6:.1f}M" if tokens else "-",
            "**VOID**" if d.name in cs.VOID_BATCHES else "",
        ))

    lines = [
        "# Batch inventory",
        "",
        "Generated by `repro/freeze_manifest.py` from the raw artefacts. `R/C0` are the",
        "run counts per arm; `tokens` is `-` for batches that predate the recording proxy.",
        "",
        f"**{len(rows)} batches, {total_runs} run artefacts, "
        f"{total_tokens / 1e6:.1f}M accounted tokens.**",
        "",
        "| batch | payload(s) | policy | runs | R/C0 | tokens | |",
        "|---|---|---|---:|---|---:|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(x) for x in row) + " |")
    lines += [
        "",
        "A void batch is kept rather than deleted: its `VOID.md` records what broke, and a",
        "batch that is missing from the directory listing is indistinguishable from one that",
        "never ran.",
        "",
    ]
    INVENTORY.write_text("\n".join(lines), encoding="utf-8")
    print(f"INVENTORY.md: {len(rows)} batches, {total_runs} runs, "
          f"{total_tokens / 1e6:.1f}M tokens")
    return 0


def main() -> int:
    manifest()
    inventory()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
